### PR TITLE
Update generators

### PR DESCRIPTION
**Pull request by jolheiser**
This is a PR to clean up some of the generators in `data`.

Let me know if you have any thoughts/questions/concerns with this implementation. 🙂 

1. Sets the build tag to `generate`
   - > The go generate tool also sets the build tag "generate" so that files may be examined by go generate but ignored during build. 
 2. Moves all generators out next to their generated file and sets a build tag like above.
 3. Adds a new README in `data` to explain how to update the generators.

**NOTE:** `block.go` will likely change with every `go generate` invocation because `NeedsTools` is a map and the AST generator uses Go maps, which are always in random order.  
I've included the changes _this_ time because I changed the generator itself and wanted to include the results, but if you look at the diff you can see nothing really changed except the map order.

### CODE REVIEW

**Comment by Tnze** [comment]
Thanks a lot. I've long wanted to get fix of this pile of things!

**Comment by jolheiser** [comment]
I've also updated the item generator, which did not have a `go generate` tag at all and appears to be out of date.

**Comment by jolheiser** [comment]
@Tnze Let me know if you'd like me to revert https://github.com/Tnze/go-mc/pull/113/commits/f0ad375d5447e6b2b41ce11e1d4f8e275491934c

I added a helper that leverages the GitHub API to check for the files automatically based on the version. 

Pro: Only need to update the version in a single spot, if the generator can't find an appropriate file it will log and continue

Con: I'm not sure if changes are made retroactively to those files very often and if that's something we'd update accordingly in this lib or not...  
This also depends on data being updated for each patch version, otherwise generators may miss a version.

**Comment by Tnze** [comment]
No automatically check plz. Just update it manually.

**Comment by Tnze** [comment]
And..

Could you please help to change them all to using `text/templates`？Print code with `fmt.Sprint` looks stupid, and `go/ast` is no better

**Comment by jolheiser** [comment]
> Could you please help to change them all to using `text/templates`？Print code with `fmt.Sprint` looks stupid, and `go/ast` is no better

I agree with replacing `fmt`-style printing, but considering we print Go code I think `go/ast` is probably still a decent solution for the rest. (even with the map ordering output)

**Comment by jolheiser** [comment]
They should all be using templates now. 

Some of them are re-formatted into multi-line rather than single, it makes the templates much easier to look at (and ultimately lines are free).

Also discovered that sounds weren't correctly updating as well, so that should be fixed. 😅 

Let me know if you have more feedback.

**Comment by Tnze** [comment]
Thank you very much for your contribution. Everything looks great.

**Comment by jolheiser** [comment]
One last commit, just extracting `version` from the URLs to simplify the update process, less chance to mess up the URL. 🙂

**Comment by Tnze** [comment]
Just make it "ready for review" when are you done.

**Pull request merged**
