### PR TITLE
Updated events to be more readable and added the OnRespawn event

### PR DESCRIPTION
**Pull request by Computeiful**
Added a basic OnRespawn event and renamed some of the events to be more readable and consistent

### CODE REVIEW

**Comment by Computeiful** [comment]
This PR is a good reminder of why developers shouldn't make commits in the middle of the night while half-asleep.

**Comment by Tnze** [comment]
This is not backward compatible.
Maybe we should wait for next version.

**Comment by Computeiful** [comment]
Which part is not backwards compatible? 

We could wait for 1.16 before merging this PR, though I'm not sure when that will be released as 1.16 is meant to contain a huge amount of new content.

**Comment by Tnze** [comment]
For example. Maybe someone's

**Comment by Computeiful** [comment]
Hmm yes, you're quite right there. In that case we should not merge this PR until we release a 1.16 compatible version.

**Comment by Tnze** [comment]
> Which part is not backwards compatible?
> 
> We could wait for 1.16 before merging this PR, though I'm not sure when that will be released as 1.16 is meant to contain a huge amount of new content.

Just wait for 1.15.3.
Actually I plan to move `github.com/Tnze/go-mc/bot` to `github.com/go-mc/bot`. Do some redesign like this PR by the way.

**Comment by Computeiful** [comment]
In that case I shall wait for the move to `github.com/go-mc/bot` before making any new pull requests.

**Comment by Computeiful** [comment]
This branch can now be considered outdated and stale.

**Pull request closed without merging**
