### PR TITLE
Auto-generate sound ids and names

### PR DESCRIPTION
**Pull request by spbinns**

### CODE REVIEW

**Comment by Tnze** [comment]
Where is the gen_soundIDs.go ?

**Comment by Tnze** [comment]
Looks like it doesn't work on Windows. There is no `bash` there.
And the `DO NOT EDIT.` line should on the top of the generated file. ?

Sorry for the inconvenience.

**Comment by spbinns** [comment]
> Looks like it doesn't work on Windows. There is no `bash` there.
> And the `DO NOT EDIT.` line should on the top of the generated file. ?
> 
> Sorry for the inconvenience.

No problem.  I modeled it after gen_packetIDs.go.  I don't mind changing it.

**Comment by Tnze** [comment]
Thank you

**Pull request merged**
