### PR TITLE
Update blocks items and entities to 1.19.4

### PR DESCRIPTION
**Pull request by tauraamui**

### CODE REVIEW

**Comment by Tnze** [comment]
You also updated the data/lang. What's the version?

**Comment by tauraamui** [comment]
I don't know, all I did was manually update the version string within `gen_item.go` and `gen_entity.go` to match the latest available version from `minecraft-data` and ran `go generate ./...`, it looks as if you have code which is included in the `go generate` build tags which auto downloads a `"language.json"` from somewhere,

**Comment by Tnze** [comment]
There are these lines in gen_langs.go file:
```go
//go:generate go run $GOFILE
//go:generate go fmt ./...
```
So if you execute `go generate ./...`, it regenerates the language files.

**Comment by tauraamui** [comment]
> There are these lines in `gen_lang.go` file:
> 
> ```go
> //go:generate go run $GOFILE
> //go:generate go fmt ./...
> ```
> 
> So if you execute `go generate ./...`, it regenerates the language files.

I was attempting to follow the instructions provided in the data/README.md, which implied that running the full `go generate.go ./...` was appropriate as it would only affect the generators for whose version numbers had been amended.
Screenshot 2023-06-21 at 12 28 55

**Comment by tauraamui** [comment]
> You also updated the data/lang. What's the version?

Looking at the code that reads `https://piston-meta.mojang.com/mc/game/version_manifest_v2.json` it looks as though the language was updated to `1.20.1`.

**Comment by Tnze** [comment]
I prefer the langs to be updated separately. Please

**Comment by tauraamui** [comment]
> I prefer the langs to be updated separately. Please

How can I update blocks?

**Comment by Tnze** [comment]
Complicated, update the .nbt files by running the java program, and run the generator.

**Comment by tauraamui** [comment]
> I prefer the langs to be updated separately. Please

I have now reverted the language changes.

**Comment by Tnze** [comment]
> > Complicated, update the .nbt files by running the java program, and run the generator.
> 
> 
> 
> How can I do that?

Use the MCP-Reborn or Yarn projects.

**Comment by tauraamui** [comment]
I can probably find sometime this week to update the blocks, it might be easier if you can provide clear instructions on how to do so, if not don't worry. In the meantime, is this PR now ok?

**Comment by Tnze** [comment]
I will update it when I have time to upgrade the library to 1.20.x, don't worry.

I'd like to merge this PR before tag the final v1.19.x

**Comment by tauraamui** [comment]
> I will update it when I have time to upgrade the library to 1.20.x, don't worry.
> 
> I'd like to merge this PR before tag the final v1.19.x

Great, thank you. If you could write down the steps you follow as you do it, if you have time that'd be awesome, cos then i could update it for myself whenever I need to if you're not available, or if it's a long running PR etc.,

**Comment by tauraamui** [comment]
> I will update it when I have time to upgrade the library to 1.20.x, don't worry.
> 
> I'd like to merge this PR before tag the final v1.19.x

Just to clarify, do you mean to say here that you'll update this PR with block updates?

**Comment by Tnze** [comment]
> > I will update it when I have time to upgrade the library to 1.20.x, don't worry.
> 
> > 
> 
> > I'd like to merge this PR before tag the final v1.19.x
> 
> 
> 
> Just to clarify, do you mean to say here that you'll update this PR with block updates?

No, I will merge this PR, and make a tag v1.19.4, then update blocks and langs ..etc to 1.20.

**Comment by Tnze** [comment]
I'm sorry that I missed some messages.

> README.md should be updated by yourself to convey these otherwise unknown side effects. 

Thanks for the feedback. I'll make it clearer. The guide is telling you how to upgrade to the latest version, and manually update the version number is a disadvantage of the current plan. It's because they didn't always have the latest data updated.

I'm trying to get rid of PrismarineJS/minecraft-data. We have `data/blocks` before, but I have successfully moved it to `/level` and no longer related other projects anymore.



> Where can you control/set the language version to use? It seems to just fetch the latest without any control over it.

Yes, it's designed to find the latest version and could not be controlled.

**Comment by tauraamui** [comment]
> I'm sorry that I missed some messages.
> 
> > README.md should be updated by yourself to convey these otherwise unknown side effects.
> 
> Thanks for the feedback. I'll make it clearer. The guide is telling you how to upgrade to the latest version, and manually update the version number is a disadvantage of the current plan. It's because they didn't always have the latest data updated.

Nice, makes sense. Thanks!
> 
> I'm trying to get rid of PrismarineJS/minecraft-data. We have `data/blocks` before, but I have successfully moved it to `level/block` and no longer related other projects anymore.

Yes I kind of noticed the mixed reliance on this repo, I can't help but notice that their extraction process is over engineered and also not updated very often, as a project whose entire purpose is to track the latest versions of MC this seems inadequate. It sounds like an optional "builtin" to `go-mc` process to do manual extractions would be preferable.
> 
> > Where can you control/set the language version to use? It seems to just fetch the latest without any control over it.
> 
> Yes, it's designed to find the latest version and could not be controlled.

I understand, given that we might always want to update to MC versions previous to the latest release, because I think it might be a good idea for this library to have tags for every version from now to the latest version (some servers take a while to update etc.,) could I raise a PR which allows a specific language version to be selected?

**Comment by Tnze** [comment]
> could I raise a PR which allows a specific language version to be selected?

I'm glad to merge such a feature.

**Comment by tauraamui** [comment]
> > could I raise a PR which allows a specific language version to be selected?
> 
> I'm glad to have such a feature.

Working on it: https://github.com/tauraamui/go-mc/tree/feat/define-target-lang-for-generate

I have some questions, where would be better to communicate with you?

**Comment by Tnze** [comment]
Discord is ok. To get the fastest response, you can contact me on Tencent QQ.

**Pull request merged**
