### PR TITLE
Bump protocol to 1.17.1

### LINKED ISSUE #111: Change protocol version to var
Rather than a `const`, what about making it a `var`?

Reason being it would allow a little flexibility for patch version changes, e.g. right now I cannot join `1.17.1` servers until there is a new version of this library with an incremented protocol number.
The current workaround is to change the code in my module cache, but that's not a great long-term solution.

I would be more than happy to submit a PR for this, or if you have an alternative you'd prefer. :slightly_smiling_face: 

https://github.com/Tnze/go-mc/blob/6500fbeaab50c9fa0e589d0e9e442dde943a4c9d/bot/mcbot.go#L20

I know there are changes between versions, but to my knowledge patch versions usually don't change much.

### PR DESCRIPTION
**Pull request by jolheiser**
I updated and ran the generators followed by `go fmt ./...`, looks like no change in output. 

Let me know if something else needs to be done. :slightly_smiling_face: 

Closes #111

### CODE REVIEW

**Comment by Tnze** [comment]
Thanks!

You need execute the generators by using `go generate` command.

**Comment by Tnze** [comment]
Those generators are written by different people and the configuration may not be "such good".

I intend to combine some generators into one and make them work better with go generate.

**Comment by Tnze** [comment]
I means, for example, `go generate ./data/...`.

**Comment by jolheiser** [comment]
`go generate` did not produce any further output.

**Comment by Tnze** [comment]
What about `go generate ./data/packetid/gen/packetIDs.go`?

**Comment by jolheiser** [comment]
It logs the message that it's running, however there are no changes according to git.

**Comment by Tnze** [comment]
Please help to see what happened.
raw.githubusercontent.com is not available in my country in these days.

**Comment by jolheiser** [comment]
There doesn't seem to be any issues, I think there were just no protocol changes in this patch version.
[protocol.1.17.0.json.txt](https://github.com/Tnze/go-mc/files/6911924/protocol.1.17.0.json.txt)
[protocol.1.17.1.json.txt](https://github.com/Tnze/go-mc/files/6911925/protocol.1.17.1.json.txt)

**Comment by Tnze** [comment]
Please also update the `data/lang`, `data/item`, `data/block` and `data/entity` package.

**Comment by jolheiser** [comment]
lang required an update, but the others did not.
https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc/1.17.1

**Comment by Tnze** [comment]
And the version number in README plz.

**Comment by jolheiser** [comment]
Done.

Version

**Pull request merged**
