### PR TITLE
Receive World Information when Changing Dimension 

### PR DESCRIPTION
**Pull request by patyhank**
https://github.com/Tnze/go-mc/discussions/166

The Dimension MinY and Height may changed when respawn

### CODE REVIEW

**Comment by Tnze** [comment]
Seems like you don't have scanned the whole packet. Why

**Comment by patyhank** [comment]
等等補上

**Comment by Tnze** [comment]
测试过了吗，测过我就合了

**Comment by patyhank** [comment]
測過了 正常

**Pull request merged**
