### PR TITLE
Update downloader for 1.17, fix small bug in en_us generator, and regen languages for 1.17

### PR DESCRIPTION
**Pull request by eneev-a**
When running daze example against 1.17 server I've got a mis-formatted error message which I traced to lack of English translation for "multiplayer.disconnect.incompatible".

This PR fixes the translation.

### CODE REVIEW

**Comment by Tnze** [comment]
I'm confused about the changing "Do not depend on chat package from en_us.go".
Can you explain the purpose of that commit?

**Comment by eneev-a** [comment]
That commit fixes a bug in the downloader.go.
If the generated en_us.go depends on the chat package, we end up having a cyclic dependency: chat.go -> en_us.go -> chat.go.

The cycle is broken by the condition in the template that roughly says "if this is en-us, do not import chat package".

The "if this is en-us" condition in the template is broken,  because it compares `PkgName` with string "en_us". But `PkgName` is set to `pName`, and `pName` is set to `strings.ReplaceAll(name, "_", "-")`, so `PkgName` can never be equal to "en_us" -- all underscores in it have been replaced with a dash.

The `Name` field though has the dashes. So that commit uses the `Name` instead of `PkgName`.

**Comment by eneev-a** [comment]
Thank you for the review.

**Comment by Tnze** [comment]
And thank you very much for your work.

**Pull request merged**
